name: Release

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-clean
        uses: docker/metadata-action@v3
        with:
          images: cciobanu98/clean-poc

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: src/WebUI/Dockerfile
          context: src
          push: true
          tags: ${{ steps.meta-clean.outputs.tags }}
          labels: ${{ steps.meta-clean.outputs.labels }}

  release:
    needs: [build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: deployment
          linting: off